[package]
name = "micro-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "micro"
path = "src/main.rs"

[dependencies]
libc = "0.2"
micro-agent = { workspace = true }
micro-auth = { workspace = true }
micro-commands = { workspace = true }
micro-config = { workspace = true }
micro-context = { workspace = true }
micro-dirs = { workspace = true }
micro-extensions = { workspace = true }
micro-models = { workspace = true }
micro-provider = { workspace = true }
micro-remote = { workspace = true }
micro-rpc = { workspace = true }
micro-sandbox = { workspace = true }
micro-session = { workspace = true }
micro-skills = { workspace = true }
micro-prompts = { workspace = true }
micro-mcp = { workspace = true }
micro-tools = { workspace = true }
micro-tui = { workspace = true }
micro-types = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
fs2 = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
micro-extensions = { workspace = true }
