[package]
name = "micro-remote"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
micro-types = { workspace = true }

aes-gcm = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
hkdf = { workspace = true }
hmac = { workspace = true }
qrcode = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
x25519-dalek = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
x25519-dalek = { workspace = true }
reqwest = { workspace = true }
